#!/usr/bin/env bash
# the script desplay the defnition of the osi model and how it is organized

echo "The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology"

echo "3"

